spring:
  application:
    name: wondollar

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:wondollar
    username: sa
    password:
    driver-class-name: org.h2.Driver


server:
  servlet:
    encoding:
      force-response: true
