spring:
  application:
    name: wondollar

  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5

  datasource:
    url: jdbc:h2:mem:wondollar
    username: sa
    password:
    driver-class-name: org.h2.Driver


server:
  servlet:
    encoding:
      force-response: true
